spring:
  data:
    mongodb:
      database: e_lib_db
      port: 27017
      host: localhost

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.borodkin.elibrary.changelogs