DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;

CREATE TABLE GENRES
(
    ID INT IDENTITY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE AUTHORS
(
    ID INT IDENTITY,
    FULL_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE BOOKS
(
    ID INT IDENTITY,
    TITLE VARCHAR(255) NOT NULL,
    GENRE_ID INT NOT NULL,
    AUTHOR_ID INT NOT NULL,
    FOREIGN KEY(GENRE_ID) REFERENCES GENRES(ID),
    FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(ID)
);
